services:
  db_server:
    build:
      context: ./db_server
    container_name: db_server
    environment:
      BACKUP_PASSPHRASE: ${BACKUP_PASSPHRASE:-SuperSecretPass123!}
      BACKUP_TARGET_HOST: backup_server
      BACKUP_TARGET_PATH: /incoming
      DB_NAME: app_db
    ports:
      - "3306:3306"
      - "2222:22"
    networks:
      public_net:
        ipv4_address: 172.30.0.2
      private_net:
        ipv4_address: 172.30.0.18
    restart: always

  backup_server:
    build:
      context: ./backup_server
    container_name: backup_server
    environment:
      BACKUP_PASSPHRASE: ${BACKUP_PASSPHRASE:-SuperSecretPass123!}
      GITHUB_REPO_URL: ${GITHUB_REPO_URL:-https://github.com/PrashnaSub10/two_servers.git}
      GIT_USER_NAME: ${GIT_USER_NAME:-Backup Bot}
      GIT_USER_EMAIL: ${GIT_USER_EMAIL:-backup-bot@example.com}
      GITHUB_TOKEN: ${GITHUB_TOKEN:-}
    networks:
      private_net:
        ipv4_address: 172.30.0.19
    restart: always

networks:
  public_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/28
          gateway: 172.30.0.1

  private_net:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 172.30.0.16/28
          gateway: 172.30.0.17
